[package]
name = "kuramoto-db"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0"
redb = "2.6.0"
async-trait = "0.1.88"
tempfile = "3.20.0"
tokio = { version = "1.43", features = ["rt", "macros", "sync"] }

rand = { version = "0.9.1" }
getrandom = { version = "0.3.3", features = ["wasm_js"] }
uuid = "1.17.0"

[features]
riblt_debug = []
