[profile.default]
# Fail any individual test that runs longer than this duration.
test-timeout = "10s"

# Optional: fail fast per-test, no retries.
retries = 0

# Optional: surface status as soon as tests finish.
status-level = "pass"

# You can define other profiles (e.g., ci) and override timeouts if needed.
[profile.ci]
inherits = "default"
test-timeout = "15s"
retries = 0
status-level = "fail"

# Local profile with a 20s per-test timeout for diagnosing slow tests
[profile.twenty]
inherits = "default"
test-timeout = "20s"
retries = 0
status-level = "pass"
